[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oxp-mce-helper"
version = "0.1.0"
authors = [
    { name = "Outshift Open", email = "oss@cisco.com" }
]
license = "Apache-2.0"
description = "MCE helper interfaces"
requires-python = ">=3.13,<3.15"
dependencies = [
    "oxp-mce-core>=2.0.0rc1",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["mce.helper*"]
namespaces = true

[tool.uv.sources]
oxp-mce-core = { workspace = true }