[project]
name = "oxp-api"
version = "1.0.0"
authors = [
    { name = "Outshift Open", email = "oss@cisco.com" }
]
license = "Apache-2.0"
description = "OXP backend API service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clickhouse-connect>=0.11.0",
    "clickhouse-sqlalchemy>=0.3.2",
    "fastapi>=0.129.0",
    "neo4j>=6.1.0",
    "packaging>=26.0",
    "numba>=0.60.0",
    "numpy>=2.3.5",
    "pydantic-settings>=2.13.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "redis>=5.0.0",
    "sqlalchemy>=2.0.46",
    "umap-learn>=0.5.7",
    "uvicorn>=0.41.0",
    "ruff<=0.15.22",
    "oxp-ontology[models,verify]>=1.0.1",
]



[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["oxp"]

[project.scripts]
dev = "oxp.app:main"

[dependency-groups]
dev = [
    "fakeredis>=2.0.0",
    "httpx>=0.28.1",
    "oxp-mce-provider-native",
    "oxp-mce-provider-sdk",
    "pytest>=9.0.2",
]

[tool.uv]
environments = ["sys_platform == 'linux' or sys_platform == 'darwin'"]
