# Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

"""Tests for oxp_ontology.verification (instance-level SHACL conformance checks).

Requires the ``verify`` extra (pyshacl) and the generated Pydantic models
(``models.nodes``) — regenerated by CI before this file runs, same as
test_models.py. Running `python scripts/generate_models.py` locally first is
required to run this file directly.
"""

import datetime

import pydantic
import pytest

from oxp_ontology.verification import (
    KGVerificationReport,
    OntologyValidationError,
    ShapeViolation,
    verify_kg_object,
)

pyshacl = pytest.importorskip("pyshacl")


def _consistency_report(*, with_group=True, **overrides):
    """Return (node, edges) -- ofSemanticGroup is a real KGEdge class, not a
    field on ConsistencyReport, so it can't be passed as a node kwarg (that's
    now a pydantic extra_forbidden error). Pass the edges to verify_kg_object
    separately; with_group=False omits it, to test the mandatory-property
    violation."""
    from oxp_ontology.models.edges.of_semantic_group import ofSemanticGroup
    from oxp_ontology.models.nodes.consistency_report import ConsistencyReport

    defaults = {
        "id": "consistency-1",
        # dataType deliberately not 'metric' here: aboutMetric then becomes
        # mandatory (AnalysisElementAboutMetricShape) and points at a
        # mas:Metric node, which a single-instance graph can't establish --
        # see TestConditionalAboutMetricRule below for the part of that rule
        # this validation path *can* exercise.
        "dataType": "text",
        "mean": 0.87,
        "confidenceInterval": '{"lower": 0.8, "upper": 0.9}',
        "confidenceIndicator": "high",
    }
    defaults.update(overrides)
    node = ConsistencyReport(**defaults)
    edges = (
        [ofSemanticGroup(source_id=node.id, target_id="grp_42")] if with_group else []
    )
    return node, edges


def _anomaly_report(*, with_group=True, **overrides):
    from oxp_ontology.models.edges.of_semantic_group import ofSemanticGroup
    from oxp_ontology.models.nodes.anomaly_report import AnomalyReport

    defaults = {
        "id": "anomaly-1",
        "dataType": "text",
        "scores": "[0.1, 0.2, 0.9]",
        "threshold": 0.5,
    }
    defaults.update(overrides)
    node = AnomalyReport(**defaults)
    edges = (
        [ofSemanticGroup(source_id=node.id, target_id="grp_42")] if with_group else []
    )
    return node, edges


def _normal_behaviour_report(*, with_group=True, **overrides):
    from oxp_ontology.models.edges.of_semantic_group import ofSemanticGroup
    from oxp_ontology.models.nodes.normal_behaviour_report import (
        NormalBehaviourReport,
    )

    defaults = {
        "id": "normal-1",
        "dataType": "graph",
        "rawResult": "{}",
        "centroid": "0.5",
    }
    defaults.update(overrides)
    node = NormalBehaviourReport(**defaults)
    edges = (
        [ofSemanticGroup(source_id=node.id, target_id="grp_42")] if with_group else []
    )
    return node, edges


def _insight(*, with_concerns=True, **overrides):
    from oxp_ontology.models.edges.concerns import concerns
    from oxp_ontology.models.nodes.insight import Insight

    defaults = {
        "id": "insight-1",
        # dataType is inherited from AnalysisElement (mandatory on every
        # subclass, not just the group-scoped reports) -- 'text' since an
        # Insight is a rendered natural-language description.
        "dataType": "text",
        "templateId": "high_cost_agent",
        "description": "Agent X spent 3x the median cost for this workload.",
        "targetNodeId": "agent-x",
        "createdAt": datetime.datetime(2026, 1, 1, tzinfo=datetime.timezone.utc),
    }
    defaults.update(overrides)
    node = Insight(**defaults)
    edges = [concerns(source_id=node.id, target_id="agent-x")] if with_concerns else []
    return node, edges


class TestValidObjectsConform:
    def test_consistency_report_conforms(self):
        node, edges = _consistency_report()
        report = verify_kg_object(node, edges=edges)

        assert isinstance(report, KGVerificationReport)
        assert report.conforms is True
        assert report.errors == []

    def test_anomaly_report_conforms(self):
        node, edges = _anomaly_report()
        report = verify_kg_object(node, edges=edges)

        assert report.conforms is True
        assert report.errors == []

    def test_normal_behaviour_report_conforms(self):
        node, edges = _normal_behaviour_report()
        report = verify_kg_object(node, edges=edges)

        assert report.conforms is True
        assert report.errors == []

    def test_insight_conforms(self):
        node, edges = _insight()
        report = verify_kg_object(node, edges=edges)

        assert report.conforms is True
        assert report.errors == []


class TestMandatoryPropertyViolations:
    def test_missing_inherited_mandatory_property_fails(self):
        """ofSemanticGroup is inherited from SemanticAnalysisReport, not declared on ConsistencyReport itself."""
        node, edges = _consistency_report(with_group=False)
        report = verify_kg_object(node, edges=edges)

        assert report.conforms is False
        assert any(
            v.path == "ofSemanticGroup" and v.severity == "Violation"
            for v in report.errors
        )

    def test_missing_own_mandatory_property_fails(self):
        """mean is sh:minCount 1 + sh:severity sh:Violation, so the generator
        makes it a genuinely pydantic-required field -- a caller can't even
        construct a ConsistencyReport without it, before this ever reaches
        verify_kg_object."""
        with pytest.raises(pydantic.ValidationError):
            _consistency_report(mean=None)

    def test_missing_mandatory_property_deduplicates_across_abstract_and_concrete_shape(
        self,
    ):
        """SemanticAnalysisReportShape (targeted via subclass entailment) and
        ConsistencyReportShape both check ofSemanticGroup; the same violation
        must not be reported twice."""
        node, edges = _consistency_report(with_group=False)
        report = verify_kg_object(node, edges=edges)

        group_violations = [v for v in report.violations if v.path == "ofSemanticGroup"]
        assert len(group_violations) == 1

    def test_anomaly_report_missing_mandatory_property_fails(self):
        with pytest.raises(pydantic.ValidationError):
            _anomaly_report(scores=None)

    def test_normal_behaviour_report_missing_mandatory_property_fails(self):
        with pytest.raises(pydantic.ValidationError):
            _normal_behaviour_report(rawResult=None)

    def test_insight_missing_mandatory_template_id_fails(self):
        with pytest.raises(pydantic.ValidationError):
            _insight(templateId=None)


class TestRecommendedPropertyWarningsDoNotBlock:
    def test_missing_recommended_properties_still_conforms(self):
        """Regression test: a Warning-severity sh:property with no sh:minCount never
        fires at all (sh:datatype alone is vacuously true on an absent property).
        All recommended properties added for these shapes pair sh:minCount 1 with
        sh:severity sh:Warning so they are enforced as warnings, not silently inert.

        confidenceInterval/confidenceIndicator are str fields with a
        type-safe "" default (not Optional[str] = None) -- "missing" is
        represented by simply omitting the kwarg, not by passing None
        (which pydantic now rejects outright for a non-Optional field)."""
        from oxp_ontology.models.edges.of_semantic_group import ofSemanticGroup
        from oxp_ontology.models.nodes.consistency_report import ConsistencyReport

        node = ConsistencyReport(
            id="consistency-1",
            dataType="text",
            mean=0.87,
        )
        report = verify_kg_object(
            node, edges=[ofSemanticGroup(source_id=node.id, target_id="grp_42")]
        )

        assert report.conforms is True
        assert report.errors == []
        warning_paths = {v.path for v in report.warnings}
        assert {"confidenceInterval", "confidenceIndicator"} <= warning_paths

    def test_insight_missing_recommended_properties_still_conforms(self):
        """description is a str field with a type-safe "" default -- see the
        note above on why "missing" means omitting the kwarg, not None."""
        from oxp_ontology.models.edges.concerns import concerns
        from oxp_ontology.models.nodes.insight import Insight

        node = Insight(
            id="insight-1",
            dataType="text",
            templateId="high_cost_agent",
            targetNodeId="agent-x",
            createdAt=datetime.datetime(2026, 1, 1, tzinfo=datetime.timezone.utc),
        )
        report = verify_kg_object(
            node, edges=[concerns(source_id=node.id, target_id="agent-x")]
        )

        assert report.conforms is True
        warning_paths = {v.path for v in report.warnings}
        assert {"description"} <= warning_paths


class TestDecimalCasting:
    def test_float_field_declared_as_xsd_decimal_does_not_spuriously_fail_datatype_check(
        self,
    ):
        """rdflib's automatic literal typing maps a Python float to xsd:double; the
        ontology declares mean etc. as xsd:decimal. Without the explicit
        cast in _literal_for, a valid float value would fail sh:datatype xsd:decimal."""
        node, edges = _consistency_report(mean=0.5)
        report = verify_kg_object(node, edges=edges)

        assert report.conforms is True
        assert not any(v.path == "mean" for v in report.violations)


class TestConditionalAboutMetricRule:
    def test_metric_data_type_without_about_metric_fails(self):
        """mas:AnalysisElementAboutMetricShape: dataType='metric' requires
        aboutMetric. This only exercises the failing half -- confirming a
        present, correctly-typed aboutMetric conforms would need the target
        Metric node's own rdf:type in the same graph, which a single
        instance's own fields can't supply (see verify_kg_object docstring:
        it validates one constructed object, not a connected graph)."""
        node, edges = _consistency_report(dataType="metric")
        report = verify_kg_object(node, edges=edges)

        assert report.conforms is False
        assert any(
            v.severity == "Violation" and "aboutMetric" in v.message
            for v in report.errors
        )


class TestOntologyValidationError:
    def test_raised_from_a_failing_report_carries_the_report(self):
        node, edges = _consistency_report(with_group=False)
        report = verify_kg_object(node, edges=edges)
        assert report.conforms is False

        exc = OntologyValidationError(report)

        assert exc.report is report
        assert "ConsistencyReport failed ontology validation" in str(exc)
        assert "ofSemanticGroup" in str(exc)

    def test_raised_from_a_report_with_no_errors_falls_back_to_placeholder_text(self):
        report = KGVerificationReport(kg_type="Whatever", conforms=False, violations=[])

        exc = OntologyValidationError(report)

        assert "unknown violation" in str(exc)


class TestUnknownClass:
    def test_unrecognized_kg_type_raises_value_error(self):
        class _NotAnOntologyClass:
            kg_type = "TotallyMadeUpClassName"
            kg_id = None

            def model_dump(self, mode="python", exclude_none=True):
                return {}

        with pytest.raises(ValueError, match="TotallyMadeUpClassName"):
            verify_kg_object(_NotAnOntologyClass())


def test_shape_violation_is_a_plain_dataclass():
    violation = ShapeViolation(
        path="groupId", severity="Violation", message="must have groupId"
    )

    assert violation.path == "groupId"
    assert violation.severity == "Violation"
