# Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

"""Smoke tests for the Pydantic KG models generated by scripts/generate_models.py.

Regenerated by CI before this file runs (see .github/workflows/test.yml) - the
files under oxp_ontology.models.nodes/edges are not committed to source
control. Running `python scripts/generate_models.py` (or `make
generate-models`) locally first is required to run this file directly.
"""

import pytest


def test_base_classes_importable():
    from oxp_ontology.models.base import KGBase, KGEdge, KGNode

    assert issubclass(KGNode, KGBase)
    assert issubclass(KGEdge, KGBase)


def test_generated_node_and_edge_directories_are_populated():
    from pathlib import Path

    import oxp_ontology.models as models_pkg

    # oxp_ontology.models has no __init__.py (implicit PEP 420 namespace
    # package, matching the generator's own nodes/edges output dirs), so it
    # has no __file__ - only __path__.
    models_dir = Path(next(iter(models_pkg.__path__)))
    nodes = list((models_dir / "nodes").glob("*.py"))
    edges = list((models_dir / "edges").glob("*.py"))

    # Weak lower bounds, not exact counts - the ontology grows over time and
    # this should not need updating every time a class/property is added.
    assert len(nodes) > 20, "expected generation to produce many node models"
    assert len(edges) > 20, "expected generation to produce many edge models"


def test_agent_call_node_round_trips_to_json():
    from oxp_ontology.models.nodes.agent_call import AgentCall

    node = AgentCall(
        id="call-1",
        sessionId="session-1",
        startTime=0.0,
        endTime=1.0,
        duration=1000.0,
    )
    payload = node.to_json()

    assert payload["id"] == "call-1"
    assert payload["node_type"] == "AgentCall"


def test_mandatory_field_missing_raises_at_construction():
    """id/sessionId/startTime/endTime/duration are sh:minCount 1 +
    sh:severity sh:Violation on Element/ExecutionElement -- the generator
    makes those genuinely pydantic-required, so a caller can't even
    construct an object missing one (fails fast, before it ever reaches
    verify_kg_object)."""
    from pydantic import ValidationError

    from oxp_ontology.models.nodes.agent_call import AgentCall

    with pytest.raises(ValidationError):
        AgentCall(sessionId="session-1", startTime=0.0, endTime=1.0, duration=1000.0)


def test_contains_session_edge_round_trips_to_json_and_jsonld():
    from oxp_ontology.models.edges.contains_session import containsSession

    edge = containsSession(source_id="group-1", target_id="session-1")
    payload = edge.to_json()

    assert payload["from_id"] == "group-1"
    assert payload["to_id"] == "session-1"
    assert payload["edge_type"] == "containsSession"

    jsonld = edge.to_jsonld()
    assert jsonld["@type"] == "mas:containsSession"
    assert jsonld["source"] == {"@id": "group-1"}
    assert jsonld["target"] == {"@id": "session-1"}


def test_node_inheritance_resolved_from_ontology_subclassing():
    """Generated node classes reflect the ontology's rdfs:subClassOf chain -
    AgentCall is a subclass of ExecutionElement, not a bare KGNode."""
    from oxp_ontology.models.nodes.agent_call import AgentCall
    from oxp_ontology.models.nodes.execution_element import ExecutionElement

    assert issubclass(AgentCall, ExecutionElement)


@pytest.mark.parametrize(
    ("module", "cls_name"),
    [
        ("session", "Session"),
        ("mas_call", "MASCall"),
        ("llm_call", "LLMCall"),
        ("tool_call", "ToolCall"),
        ("processing_call", "ProcessingCall"),
        ("state", "State"),
        ("transition", "Transition"),
    ],
)
def test_expected_core_node_classes_exist(module, cls_name):
    imported = __import__(f"oxp_ontology.models.nodes.{module}", fromlist=[cls_name])
    assert hasattr(imported, cls_name)
