{{- if .Values.externalSecrets -}}
{{- range $externalSecret := .Values.externalSecrets -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ tpl $externalSecret.name $ }}
  namespace: {{ $.Release.Namespace }}
spec:
  # SecretStoreRef defines which SecretStore to use when fetching the secret data
  secretStoreRef:
    name: {{ $externalSecret.secretStoreRef.name }}
    kind: {{ $externalSecret.secretStoreRef.kind }}

  # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h" (from time.ParseDuration)
  # May be set to zero to fetch and create it once
  refreshInterval: "1h0m0s"

  # the target describes the secret that shall be created
  # there can only be one target per ExternalSecret
  target:
    # The secret name of the resource
    # Defaults to .metadata.name of the ExternalSecret
    # It is immutable
    name: {{ tpl $externalSecret.target.name $ }}
    {{ if $externalSecret.target.template -}}
    template:
      {{- toYaml $externalSecret.target.template | nindent 6 }}
    {{- end }}

  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    {{- range $externalSecret.data }}
    - {{ . | toYaml | nindent 6 }}
    {{- end }}
---
{{- end -}}
{{- end -}}
