#!/usr/bin/env python3
# Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

"""
Generate mas-shapes.ttl (SHACL) from the OWL ontology files.

Requirement level (mandatory / recommended / optional) is NOT decided by this
script -- it lives on each property declaration directly, in the ontology
files, as standard SHACL: every owl:DatatypeProperty/owl:ObjectProperty is
dual-typed sh:PropertyShape with its own sh:path/sh:targetClass/sh:minCount/
sh:severity (see the "TODO" placeholders left there by
scripts/inject_shacl_into_properties.py; tune sh:minCount/sh:severity per
property directly in mas-ontology.ttl etc., not here).

This script only builds the class-level NodeShapes: sh:targetClass, sh:node
inheritance mirroring rdfs:subClassOf, and sh:property references to each
class's own properties -- a bare reference to the property's IRI (which is
already a complete, self-targeting PropertyShape), not a duplicate inline copy
of its constraint.

The output file (mas-shapes.ttl) is gitignored and regenerated by CI before
tests/build, exactly like the Pydantic models under models/nodes|edges/ --
never hand-edit it, changes will be silently overwritten. Anything needing
logic this generator can't produce (sh:sparql conditional/multi-hop
constraints, sh:class checks on a property's subjects/objects) belongs in
the separate hand-maintained src/oxp_ontology/mas-shapes-custom.ttl,
which this script never touches and which stays committed.

Usage: python scripts/generate_shacl_shapes.py [output.ttl]
Run from the oxp-ontology repo root, with rdflib installed.
"""

import os
import sys

from rdflib import OWL, RDF, RDFS, Graph, URIRef

PACKAGE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(PACKAGE_ROOT, "src", "oxp_ontology")

# Source ontology files -- NOT including mas-shapes.ttl itself, since this
# script generates that file.
ONTOLOGY_FILES = [
    "mas-ontology.ttl",
    "metrics-ontology.ttl",
    "semantic-ontology.ttl",
    "analysis-ontology.ttl",
    "insight-ontology.ttl",
]

PREFIXES = {
    "https://outshift-open.github.io/oxp-ontology/mas#": "mas",
    "https://outshift-open.github.io/oxp-ontology/metrics#": "metrics",
    "https://outshift-open.github.io/oxp-ontology/analysis#": "analysis",
    "http://www.w3.org/2001/XMLSchema#": "xsd",
}


def curie(uri):
    """Render a URI as prefix:localName using PREFIXES, or a full <uri> if unknown."""
    s = str(uri)
    for ns, prefix in PREFIXES.items():
        if s.startswith(ns):
            return f"{prefix}:{s[len(ns) :]}"
    return f"<{s}>"


def get_fragment(node):
    return getattr(node, "fragment", None)


def resolve_class_names(g, node):
    """Resolve a domain value to the set of class URIs it denotes, expanding
    owl:unionOf. Mirrors generate_models.py's resolver."""
    if node == OWL.Thing:
        return {OWL.Thing}
    if isinstance(node, URIRef):
        return {node}

    union_node = g.value(node, OWL.unionOf)
    if union_node:
        result = set()
        for item in g.items(union_node):
            result |= resolve_class_names(g, item)
        return result

    return set()


def main():
    output_path = (
        sys.argv[1] if len(sys.argv) > 1 else os.path.join(SRC, "mas-shapes.ttl")
    )

    g = Graph()
    for fname in ONTOLOGY_FILES:
        g.parse(os.path.join(SRC, fname), format="turtle")

    defined_classes = {
        cls for cls in g.subjects(RDF.type, OWL.Class) if isinstance(cls, URIRef)
    }

    # child -> direct parent (first non-self rdfs:subClassOf target that is
    # itself a defined class), matching generate_models.py's single-parent rule.
    parent_of = {}
    for cls in defined_classes:
        for parent in g.objects(cls, RDFS.subClassOf):
            if (
                isinstance(parent, URIRef)
                and parent in defined_classes
                and parent != cls
            ):
                parent_of[cls] = parent
                break

    properties = list(g.subjects(RDF.type, OWL.DatatypeProperty)) + list(
        g.subjects(RDF.type, OWL.ObjectProperty)
    )

    # class -> list of props declared directly on it (domain names this class
    # specifically, or owl:Thing).
    class_props = {cls: [] for cls in defined_classes}
    for prop in properties:
        domain_classes = set()
        for domain in g.objects(prop, RDFS.domain):
            domain_classes |= resolve_class_names(g, domain)
        for cls in defined_classes:
            if cls in domain_classes or OWL.Thing in domain_classes:
                class_props[cls].append(prop)

    lines = []
    lines.append("@prefix sh: <http://www.w3.org/ns/shacl#> .")
    lines.append("@prefix mas: <https://outshift-open.github.io/oxp-ontology/mas#> .")
    lines.append(
        "@prefix metrics: <https://outshift-open.github.io/oxp-ontology/metrics#> ."
    )
    lines.append(
        "@prefix analysis: <https://outshift-open.github.io/oxp-ontology/analysis#> ."
    )
    lines.append("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .")
    lines.append("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .")
    lines.append("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .")
    lines.append("@prefix owl: <http://www.w3.org/2002/07/owl#> .")
    lines.append("")
    lines.append(
        "# ============================================================================="
    )
    lines.append("#  mas-shapes.ttl -- GENERATED by scripts/generate_shacl_shapes.py")
    lines.append("#")
    lines.append("#  Class-level structure only (sh:targetClass, sh:node parent-shape")
    lines.append("#  inheritance mirroring rdfs:subClassOf, sh:property references).")
    lines.append("#")
    lines.append(
        "#  Requirement level (mandatory/recommended/optional) is NOT here -- it"
    )
    lines.append(
        "#  lives directly on each property in the ontology files (mas-ontology.ttl"
    )
    lines.append(
        "#  etc.), which dual-type every owl:DatatypeProperty/owl:ObjectProperty as"
    )
    lines.append("#  sh:PropertyShape with its own sh:path/sh:targetClass/sh:minCount/")
    lines.append(
        "#  sh:severity. Each sh:property reference below is a bare IRI, not a"
    )
    lines.append("#  duplicated inline copy -- the property IS the shape.")
    lines.append("#")
    lines.append(
        "#  To set a property's requirement level, edit sh:minCount/sh:severity on"
    )
    lines.append("#  its declaration in the ontology file, not here.")
    lines.append(
        "# ============================================================================="
    )
    lines.append("")

    for cls in sorted(defined_classes, key=lambda c: get_fragment(c) or ""):
        cls_name = get_fragment(cls)
        if not cls_name:
            continue
        shape_curie = curie(cls).replace(":" + cls_name, ":" + cls_name + "Shape")

        lines.append(f"{shape_curie}")
        lines.append("    a sh:NodeShape ;")
        lines.append(f"    sh:targetClass {curie(cls)} ;")

        parent = parent_of.get(cls)
        if parent is not None:
            parent_name = get_fragment(parent)
            parent_shape = curie(parent).replace(
                ":" + parent_name, ":" + parent_name + "Shape"
            )
            lines.append(f"    sh:node {parent_shape} ;")

        own_props = sorted(
            class_props.get(cls, []), key=lambda p: get_fragment(p) or ""
        )

        if not own_props:
            lines[-1] = lines[-1].rstrip(" ;") + " ."
            lines.append("")
            continue

        for prop in own_props[:-1]:
            lines.append(f"    sh:property {curie(prop)} ;")
        lines.append(f"    sh:property {curie(own_props[-1])} .")
        lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {output_path}")
    print(
        f"  {len(defined_classes)} classes, "
        f"{sum(len(v) for v in class_props.values())} sh:property references"
    )


if __name__ == "__main__":
    main()
