{{- range $externalSecret := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ tpl $externalSecret.name $ }}
spec:
  secretStoreRef:
    name: {{ $externalSecret.secretStoreRef.name }}
    kind: {{ $externalSecret.secretStoreRef.kind }}
  refreshInterval: {{ default "1h" $externalSecret.refreshInterval | quote }}
  target:
    name: {{ tpl $externalSecret.target.name $ }}
    {{- with $externalSecret.target.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  data:
    {{- range $externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key | quote }}
        {{- with .remoteRef.property }}
        property: {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
