#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
engine:
  max_workers: 8
  execution_strategy: hybrid

cache:
  path: null
  read: false
  write: false

metrics:
  Session:
    - Duration
    - Cost