#  Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#  SPDX-License-Identifier: Apache-2.0
import json
import pytest
from unittest.mock import patch, MagicMock
from click.testing import CliRunner
from mce.cli.main import app as cli
from mce.client.adapters.json_provider import JsonDataProvider


@pytest.fixture
def mock_provider():
    # Use JsonDataProvider pointed at demo_data.json
    # Assuming demo_data.json is in package root or known location
    # We can rely on the fact that existing tests/conftest.py might already set things up,
    # but let's be explicit and concise.
    provider = JsonDataProvider("demo_data.json")
    return provider


def test_legacy_compute_output_format(tmp_path):
    """
    Test that 'mce legacy compute' produces output matching the V1 schema.
    V1 Schema structure:
    {
        "metrics": { ... metadata ... },
        "results": {
           "session_metrics": [...],
           "span_metrics": [...],
           "failed_metrics": [...]
        }
    }
    """
    runner = CliRunner()

    # 1. Create a V1-style config file
    config_file = tmp_path / "v1_config.json"
    output_file = tmp_path / "output.json"

    # We use a known session_id from demo_data.json (generated by generate_demo_data.py)
    # The 'success_session' has id "success_session_123"
    config_data = {
        "session_id": "session_success",  # From generate_demo_data.py
        "metrics": ["ToolErrorRate"],
        "llm_config": {},
    }
    config_file.write_text(json.dumps(config_data))

    # 2. Patch OXPDataProvider to use JsonDataProvider instead.
    # legacy.py uses _get_kg_provider() — patch that factory function.
    with patch("mce.legacy.cli.legacy._get_kg_provider") as MockProviderCls:
        # Use an in-memory mock — demo_data.json is not shipped with the package
        mock_data_provider = MagicMock()
        mock_data_provider.fetch.return_value = {
            "id": "session_success",
            "session_id": "session_success",
            "tool_spans": [],
            "llm_spans": [],
        }
        MockProviderCls.return_value = mock_data_provider

        # 3. Run the command
        result = runner.invoke(
            cli, ["legacy", "compute", str(config_file), "--output", str(output_file)]
        )

        # Debug output if failed
        if result.exit_code != 0:
            print(result.output)
            print(result.exception)

        assert result.exit_code == 0

        # 4. Validate Output
        assert output_file.exists()
        with open(output_file) as f:
            data = json.load(f)

        # Top level keys
        assert "metrics" in data, "Output missing 'metrics' key (V1 schema)"
        assert "results" in data, "Output missing 'results' key (V1 schema)"

        results_obj = data["results"]
        assert isinstance(results_obj, dict), (
            "'results' should be a dictionary grouping metrics by level"
        )

        # Check for V1 groupings
        assert "session_metrics" in results_obj
        assert "span_metrics" in results_obj

        # Check that we actually got results
        # ToolErrorRate is a Session metric
        session_metrics = results_obj["session_metrics"]
        assert len(session_metrics) > 0

        metric_res = session_metrics[0]
        assert "metric_name" in metric_res
        assert metric_res["metric_name"] == "ToolErrorRate"
        # In V1 results, the key is strictly 'metric_name' ?
        # Let's verify exact V1 keys if possible, but structure of groups is the main requirement.
